CREATE TABLE tutores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    data_cadastro TIMESTAMP NOT NULL
);

CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    especie VARCHAR(80) NOT NULL,
    raca VARCHAR(80),
    idade INTEGER,
    peso NUMERIC(10,2),
    sexo VARCHAR(10) NOT NULL,
    castrado BOOLEAN NOT NULL,
    tutor_id BIGINT NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,
    CONSTRAINT fk_pets_tutores FOREIGN KEY (tutor_id) REFERENCES tutores(id)
);

CREATE TABLE veterinarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    crmv VARCHAR(30) NOT NULL UNIQUE,
    especialidade VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    email VARCHAR(160)
);

CREATE TABLE vacinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    data_aplicacao DATE NOT NULL,
    data_proxima_dose DATE,
    pet_id BIGINT NOT NULL,
    veterinario_id BIGINT,
    observacao VARCHAR(500),
    CONSTRAINT fk_vacinas_pets FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_vacinas_veterinarios FOREIGN KEY (veterinario_id) REFERENCES veterinarios(id)
);

CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    veterinario_id BIGINT NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    diagnostico VARCHAR(500),
    observacoes VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_consultas_pets FOREIGN KEY (pet_id) REFERENCES pets(id),
    CONSTRAINT fk_consultas_veterinarios FOREIGN KEY (veterinario_id) REFERENCES veterinarios(id)
);

CREATE TABLE historicos_medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    data_registro TIMESTAMP NOT NULL,
    CONSTRAINT fk_historicos_pets FOREIGN KEY (pet_id) REFERENCES pets(id)
);
